### PR TITLE
Fixed invisible navbar + added contact link.

### LINKED ISSUE #35: Nav bar
The [static prototype](https://mysociety.github.io/contract-countdown/) has navigation links in the header. This should be replicated in the codebase, to make it possible to navigate to some of the new pages that have been created, as well as back to the main filter page.

### PR DESCRIPTION
**Pull request by alexander-griffen**
Fixes #35
Currently, "Why does this matter" just sends you to your home page.

### CODE REVIEW

**Review by zarino — APPROVED** [review]
Looks good to me 👍 

I‘d be inclined to leave out the "Contact a representative" link. We’re currently assuming that people will be contacting representatives _about_ a contract, so will come via a contract page. Not sure we need this site to become a WriteToThem-style tool for open-ended discussion with reps.

**Comment by alexander-griffen** [comment]
@zarino 

Sounds good! Is it worth then, also removing the page at `contact/` that allows you to enter a postcode and then be directed to your council? That way (unless you're going via a direct url) you can only access it through a contract?

**Comment by zarino** [comment]
Yeah, I wondered whether to suggest that in #38 but figured it wouldn’t hurt just to leave it in. I think I’m still of that opinion – I don’t think it’s an issue to keep the `/contact` page accessible and functional, but just not have a link to it. It’ll be a little surprise for URL hackers ;-) And we can very easily promote it to a top level link, if we ever feel like it.

**Comment by alexander-griffen** [comment]
@zarino Sounds good! :)

**Review by struan — APPROVED** [review]

**Pull request merged**
